backend:
  name: git-gateway
  branch: main

media_folder: public/uploads
public_folder: /uploads

locale: de

collections:
  - name: settings
    label: Einstellungen
    files:
      - name: general
        label: Allgemeine Einstellungen
        file: src/content/settings/general.json
        fields:
          - { label: Seitentitel, name: siteTitle, widget: string }
          - { label: Seitenbeschreibung, name: siteDescription, widget: text }
          - { label: Hero Titel, name: heroTitle, widget: string, default: "Peter van Bohemen" }
          - { label: Hero Hintergrundbild, name: heroImage, widget: image }
          
      - name: about
        label: Über Mich
        file: src/content/settings/about.json
        fields:
          - { label: Titel, name: title, widget: string }
          - { label: Profilbild, name: image, widget: image }
          - { label: Inhalt, name: content, widget: markdown }
          
      - name: contact
        label: Kontakt
        file: src/content/settings/contact.json
        fields:
          - { label: Adresse, name: address, widget: text }
          - { label: Telefon, name: phone, widget: string }
          - { label: E-Mail, name: email, widget: string }
          - { label: Öffnungszeiten, name: hours, widget: text }

  - name: portfolio
    label: Portfolio
    folder: src/content/portfolio
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Titel, name: title, widget: string }
      - { label: Bild, name: image, widget: image }
      - { label: Alt Text, name: alt, widget: string }
      - { label: Kategorie, name: category, widget: select, options: ["wedding", "portrait", "event", "nature"] }
      - { label: Größe, name: size, widget: select, options: ["small", "medium", "large"], default: "medium" }
      - { label: Reihenfolge, name: order, widget: number, default: 0 }
      - { label: Veröffentlicht, name: published, widget: boolean, default: true }

  - name: testimonials
    label: Kundenstimmen
    folder: src/content/testimonials
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Autor, name: author, widget: string }
      - { label: Event/Anlass, name: event, widget: string, required: false }
      - { label: Bewertung, name: content, widget: text }
      - { label: Reihenfolge, name: order, widget: number, default: 0 }
      - { label: Veröffentlicht, name: published, widget: boolean, default: true }

  - name: pages
    label: Seiten
    files:
      - name: impressum
        label: Impressum
        file: src/content/pages/impressum.md
        fields:
          - { label: Titel, name: title, widget: string }
          - { label: Inhalt, name: body, widget: markdown }
          
      - name: datenschutz
        label: Datenschutz
        file: src/content/pages/datenschutz.md
        fields:
          - { label: Titel, name: title, widget: string }
          - { label: Inhalt, name: body, widget: markdown }